spring:
  datasource:
    username: root
    password: 1102Carol!
    url: jdbc:mysql://101.35.194.132:3306/softwareTesting?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  banner:
    image:
      location: OIP-C.jfif
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
server:
  IP: localhost
  port: 81
#  file:
#    name: softwareTesting.log


mybatis:
  # 配置XML映射文件中指定的实体类别名路径
  type-aliases-package: com.example.softwaretest.Entity
  # 配置MyBatis的xml配置文件路径
  mapper-locations: classpath:mapper/*.xml
#  # 开启驼峰uName自动映射到u_name
#  map-underscore-to-camel-case: true
