// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class IntegrationtestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void iTTD001001001() {
    driver.get("http://localhost:9876/homepage/home");
    driver.manage().window().setSize(new Dimension(1095, 790));
    driver.findElement(By.linkText("登录")).click();
    driver.findElement(By.cssSelector(".login-input:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".login-input:nth-child(1)")).sendKeys("zldl");
    driver.findElement(By.cssSelector(".login-input:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".login-btn")).click();
    assertThat(driver.findElement(By.cssSelector(".input-check:nth-child(4)")).getText(), is("请输入密码"));
    driver.close();
  }
  @Test
  public void iTTD001001002() {
    driver.get("http://localhost:9876/homepage/home");
    driver.manage().window().setSize(new Dimension(1095, 790));
    driver.findElement(By.linkText("登录")).click();
    driver.findElement(By.cssSelector(".login-input:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".login-input:nth-child(3)")).sendKeys("12345");
    driver.findElement(By.cssSelector(".login-btn")).click();
    assertThat(driver.findElement(By.cssSelector(".input-check:nth-child(2)")).getText(), is("用户名不能为空"));
    driver.close();
  }
  @Test
  public void iTTD001001003() {
  }
  @Test
  public void iTTD001002001() {
    driver.get("http://localhost:9876/homepage/home");
    driver.manage().window().setSize(new Dimension(1095, 790));
    driver.findElement(By.linkText("登录")).click();
    driver.findElement(By.cssSelector(".admin-login")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".admin-login"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".login-input:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".login-input:nth-child(1)")).sendKeys("mjy");
    driver.findElement(By.cssSelector(".login-input:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".login-input:nth-child(3)")).sendKeys("1234");
    driver.findElement(By.cssSelector(".login-btn")).click();
    assertThat(driver.findElement(By.cssSelector(".input-check:nth-child(4)")).getText(), is("用户名或密码错误"));
    driver.close();
  }
  @Test
  public void iTTD001003001() {
    driver.get("http://localhost:9876/homepage/home");
    driver.manage().window().setSize(new Dimension(1095, 790));
    driver.findElement(By.linkText("登录")).click();
    driver.findElement(By.cssSelector(".admin-login")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".admin-login"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".login-input:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".login-input:nth-child(1)")).sendKeys("lwy");
    driver.findElement(By.cssSelector(".login-input:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".login-input:nth-child(3)")).sendKeys("1234");
    driver.findElement(By.cssSelector(".login-btn")).click();
    assertThat(driver.findElement(By.cssSelector(".input-check:nth-child(4)")).getText(), is("用户名或密码错误"));
    driver.close();
  }
  @Test
  public void iTTD001004001() {
    driver.get("http://localhost:9876/homepage/home");
    driver.manage().window().setSize(new Dimension(1095, 790));
    driver.findElement(By.linkText("登录")).click();
    driver.findElement(By.cssSelector(".admin-login")).click();
    driver.findElement(By.cssSelector(".login-input:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".login-input:nth-child(1)")).sendKeys("mjy");
    driver.findElement(By.cssSelector(".login-input:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".login-input:nth-child(3)")).sendKeys("12345");
    driver.findElement(By.cssSelector(".login-btn")).click();
    assertThat(driver.findElement(By.cssSelector(".username")).getText(), is("mjy"));
    driver.close();
  }
  @Test
  public void iTTD001004002() {
    driver.get("http://localhost:9876/homepage/home");
    driver.manage().window().setSize(new Dimension(1095, 790));
    driver.findElement(By.linkText("登录")).click();
    driver.findElement(By.cssSelector(".login-input:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".login-input:nth-child(1)")).sendKeys("zldl");
    driver.findElement(By.cssSelector(".login-input:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".login-input:nth-child(3)")).sendKeys("12345");
    driver.findElement(By.cssSelector(".login-btn")).click();
    assertThat(driver.findElement(By.cssSelector(".section-banner-title")).getText(), is("租你想租的"));
    driver.close();
  }
  @Test
  public void iTTD001005001() {
    driver.get("http://localhost:9876/homepage/home");
    driver.manage().window().setSize(new Dimension(1095, 824));
    driver.findElement(By.linkText("登录")).click();
    driver.findElement(By.cssSelector(".login-input:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".login-input:nth-child(1)")).sendKeys("zqf");
    driver.findElement(By.cssSelector(".login-input:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".login-input:nth-child(3)")).sendKeys("12345");
    driver.findElement(By.cssSelector(".login-btn")).click();
    assertThat(driver.findElement(By.cssSelector(".input-check:nth-child(4)")).getText(), is("用户名或密码错误"));
    driver.close();
  }
  @Test
  public void iTTD001006001() {
    driver.get("http://localhost:9876/homepage/home");
    driver.manage().window().setSize(new Dimension(1095, 824));
    driver.findElement(By.linkText("登录")).click();
    driver.findElement(By.cssSelector(".login-input:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".login-input:nth-child(1)")).sendKeys("lwy");
    driver.findElement(By.cssSelector(".login-input:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".login-input:nth-child(3)")).sendKeys("12345");
    driver.findElement(By.cssSelector(".login-btn")).click();
    assertThat(driver.findElement(By.cssSelector(".input-check:nth-child(4)")).getText(), is("用户名或密码错误"));
    driver.close();
  }
  @Test
  public void iTTD002001001() {
    driver.get("http://localhost:9876/homepage/home");
    driver.manage().window().setSize(new Dimension(1095, 824));
    driver.findElement(By.linkText("登录")).click();
    driver.findElement(By.cssSelector(".register")).click();
    driver.findElement(By.cssSelector(".login-input:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".login-input:nth-child(2)")).sendKeys("12345");
    driver.findElement(By.cssSelector(".login-btn")).click();
    vars.put("result", js.executeScript("return window.location.href"));
    assertEquals(vars.get("result").toString(), "http://localhost:9876/homepage/home");
    driver.close();
  }
  @Test
  public void iTTD002001002() {
    driver.get("http://localhost:9876/homepage/home");
    driver.manage().window().setSize(new Dimension(1095, 622));
    driver.findElement(By.linkText("登录")).click();
    driver.findElement(By.cssSelector(".register")).click();
    driver.findElement(By.cssSelector(".login-input:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".login-input:nth-child(1)")).sendKeys("lwy");
    driver.findElement(By.cssSelector(".login-btn")).click();
    vars.put("result", js.executeScript("return window.location.href"));
    assertEquals(vars.get("result").toString(), "http://localhost:9876/homepage/home");
    driver.close();
  }
  @Test
  public void iTTD002002001() {
    driver.get("http://localhost:9876/homepage/home");
    driver.manage().window().setSize(new Dimension(1095, 755));
    driver.findElement(By.linkText("登录")).click();
    driver.findElement(By.cssSelector(".register")).click();
    driver.findElement(By.cssSelector(".login-input:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".login-input:nth-child(1)")).sendKeys("mjy");
    driver.findElement(By.cssSelector(".login-input:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".login-input:nth-child(2)")).sendKeys("12345");
    driver.findElement(By.cssSelector(".login-btn")).click();
    assertThat(driver.findElement(By.cssSelector(".section-banner-title")).getText(), is("租你想租的"));
    driver.close();
  }
  @Test
  public void iTTD002003001() {
    driver.get("http://localhost:9876/homepage/home");
    driver.manage().window().setSize(new Dimension(1095, 755));
    driver.findElement(By.linkText("登录")).click();
    driver.findElement(By.cssSelector(".register")).click();
    driver.findElement(By.cssSelector(".login-input:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".login-input:nth-child(1)")).sendKeys("lwyhh");
    driver.findElement(By.cssSelector(".login-input:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".login-input:nth-child(2)")).sendKeys("12345");
    driver.findElement(By.cssSelector(".login-btn")).click();
    assertThat(driver.findElement(By.cssSelector(".section-banner-title")).getText(), is("租你想租的"));
    driver.close();
  }
  @Test
  public void iTTD003001001() {
    driver.get("http://localhost:9876/homepage/home");
    driver.manage().window().setSize(new Dimension(1095, 755));
    driver.findElement(By.cssSelector(".section-banner-button")).click();
    vars.put("result", js.executeScript("return window.location.href"));
    assertEquals(vars.get("result").toString(), "http://localhost:9876/homepage/home");
    driver.close();
  }
  @Test
  public void iTTD003002001() {
    driver.get("http://localhost:9876/homepage/home");
    driver.manage().window().setSize(new Dimension(1095, 824));
    driver.findElement(By.cssSelector(".section-banner-input")).click();
    driver.findElement(By.cssSelector(".section-banner-input")).sendKeys("adad");
    driver.findElement(By.cssSelector(".section-banner-button")).click();
    vars.put("result", js.executeScript("return window.location.href"));
    assertEquals(vars.get("result").toString(), "http://localhost:9876/homepage/items?mode=2&q=adad");
    driver.close();
  }
  @Test
  public void iTTD003003001() {
    driver.get("http://localhost:9876/homepage/home");
    driver.manage().window().setSize(new Dimension(1095, 755));
    driver.findElement(By.cssSelector(".section-banner-input")).click();
    driver.findElement(By.cssSelector(".section-banner-input")).sendKeys("手表");
    driver.findElement(By.cssSelector(".section-banner-button")).click();
    vars.put("result", js.executeScript("return window.location.href"));
    assertEquals(vars.get("result").toString(), "http://localhost:9876/homepage/items?mode=2&q=%E6%89%8B%E8%A1%A8");
    driver.close();
  }
  @Test
  public void iTTD004001001() {
    driver.get("http://localhost:9876/homepage/home");
    driver.manage().window().setSize(new Dimension(1095, 790));
    driver.findElement(By.linkText("登录")).click();
    driver.findElement(By.cssSelector(".login-input:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".login-input:nth-child(1)")).sendKeys("zldl");
    driver.findElement(By.cssSelector(".login-input:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".login-btn")).click();
    assertThat(driver.findElement(By.cssSelector(".input-check:nth-child(4)")).getText(), is("请输入密码"));
    driver.close();
  }
  @Test
  public void iTTD004001002() {
    driver.get("http://localhost:9876/homepage/home");
    driver.manage().window().setSize(new Dimension(1095, 790));
    driver.findElement(By.linkText("登录")).click();
    driver.findElement(By.cssSelector(".login-input:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".login-input:nth-child(3)")).sendKeys("12345");
    driver.findElement(By.cssSelector(".login-btn")).click();
    assertThat(driver.findElement(By.cssSelector(".input-check:nth-child(2)")).getText(), is("用户名不能为空"));
    driver.close();
  }
  @Test
  public void iTTD004001003() {
  }
  @Test
  public void iTTD004002001() {
    driver.get("http://localhost:9876/homepage/home");
    driver.manage().window().setSize(new Dimension(1095, 790));
    driver.findElement(By.linkText("登录")).click();
    driver.findElement(By.cssSelector(".admin-login")).click();
    driver.findElement(By.cssSelector(".login-input:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".login-input:nth-child(1)")).sendKeys("mjy");
    driver.findElement(By.cssSelector(".login-input:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".login-input:nth-child(3)")).sendKeys("12345");
    driver.findElement(By.cssSelector(".login-btn")).click();
    assertThat(driver.findElement(By.cssSelector(".username")).getText(), is("mjy"));
    driver.close();
  }
  @Test
  public void iTTD004002002() {
    driver.get("http://localhost:9876/homepage/home");
    driver.manage().window().setSize(new Dimension(1095, 790));
    driver.findElement(By.linkText("登录")).click();
    driver.findElement(By.cssSelector(".login-input:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".login-input:nth-child(1)")).sendKeys("zldl");
    driver.findElement(By.cssSelector(".login-input:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".login-input:nth-child(3)")).sendKeys("12345");
    driver.findElement(By.cssSelector(".login-btn")).click();
    assertThat(driver.findElement(By.cssSelector(".section-banner-title")).getText(), is("租你想租的"));
    driver.close();
  }
  @Test
  public void iTTD004003001() {
    driver.get("http://localhost:9876/homepage/home");
    driver.manage().window().setSize(new Dimension(1095, 824));
    driver.findElement(By.linkText("登录")).click();
    driver.findElement(By.cssSelector(".login-input:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".login-input:nth-child(1)")).sendKeys("zqf");
    driver.findElement(By.cssSelector(".login-input:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".login-input:nth-child(3)")).sendKeys("12345");
    driver.findElement(By.cssSelector(".login-btn")).click();
    assertThat(driver.findElement(By.cssSelector(".input-check:nth-child(4)")).getText(), is("用户名或密码错误"));
    driver.close();
  }
  @Test
  public void iTTD004003002() {
    driver.get("http://localhost:9876/homepage/home");
    driver.manage().window().setSize(new Dimension(1095, 790));
    driver.findElement(By.linkText("登录")).click();
    driver.findElement(By.cssSelector(".admin-login")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".admin-login"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".login-input:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".login-input:nth-child(1)")).sendKeys("lwy");
    driver.findElement(By.cssSelector(".login-input:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".login-input:nth-child(3)")).sendKeys("1234");
    driver.findElement(By.cssSelector(".login-btn")).click();
    assertThat(driver.findElement(By.cssSelector(".input-check:nth-child(4)")).getText(), is("用户名或密码错误"));
    driver.close();
  }
  @Test
  public void iTTD005001001() {
    driver.get("http://localhost:9876/homepage/home");
    driver.manage().window().setSize(new Dimension(1095, 824));
    driver.findElement(By.linkText("登录")).click();
    driver.findElement(By.cssSelector(".register")).click();
    driver.findElement(By.cssSelector(".login-input:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".login-input:nth-child(2)")).sendKeys("12345");
    driver.findElement(By.cssSelector(".login-btn")).click();
    vars.put("result", js.executeScript("return window.location.href"));
    assertEquals(vars.get("result").toString(), "http://localhost:9876/homepage/home");
    driver.close();
  }
  @Test
  public void iTTD005002001() {
    driver.get("http://localhost:9876/homepage/home");
    driver.manage().window().setSize(new Dimension(1095, 622));
    driver.findElement(By.linkText("登录")).click();
    driver.findElement(By.cssSelector(".register")).click();
    driver.findElement(By.cssSelector(".login-input:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".login-input:nth-child(1)")).sendKeys("lwy");
    driver.findElement(By.cssSelector(".login-btn")).click();
    vars.put("result", js.executeScript("return window.location.href"));
    assertEquals(vars.get("result").toString(), "http://localhost:9876/homepage/home");
    driver.close();
  }
  @Test
  public void iTTD005003001() {
    driver.get("http://localhost:9876/homepage/home");
    driver.manage().window().setSize(new Dimension(1095, 755));
    driver.findElement(By.linkText("登录")).click();
    driver.findElement(By.cssSelector(".register")).click();
    driver.findElement(By.cssSelector(".login-input:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".login-input:nth-child(1)")).sendKeys("mjy");
    driver.findElement(By.cssSelector(".login-input:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".login-input:nth-child(2)")).sendKeys("12345");
    driver.findElement(By.cssSelector(".login-btn")).click();
    vars.put("result", js.executeScript("return window.location.href"));
    assertEquals(vars.get("result").toString(), "http://localhost:9876/homepage/home");
    driver.close();
  }
  @Test
  public void iTTD006001001() {
    driver.get("http://localhost:9876/homepage/home");
    driver.manage().window().setSize(new Dimension(1095, 783));
    driver.findElement(By.linkText("登录")).click();
    driver.findElement(By.cssSelector(".login-input:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".login-input:nth-child(1)")).sendKeys("zldl");
    driver.findElement(By.cssSelector(".login-input:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".login-input:nth-child(3)")).sendKeys("12345");
    driver.findElement(By.cssSelector(".login-btn")).click();
    driver.findElement(By.cssSelector(".section-banner-input")).click();
    driver.findElement(By.cssSelector(".section-banner-input")).sendKeys("手机");
    driver.findElement(By.cssSelector(".section-banner-button")).click();
    js.executeScript("window.scrollTo(0,686.4000244140625)");
    driver.findElement(By.cssSelector(".section-featured-card-main")).click();
    js.executeScript("window.scrollTo(0,0)");
    vars.put("result", js.executeScript("return window.location.href"));
    assertEquals(vars.get("result").toString(), "http://localhost:9876/homepage/ItemDetail/4");
    driver.close();
  }
  @Test
  public void iTTD007001001() {
    driver.get("http://localhost:9876/homepage/home");
    driver.manage().window().setSize(new Dimension(1095, 755));
    driver.findElement(By.cssSelector(".section-banner-button")).click();
    vars.put("result", js.executeScript("return window.location.href"));
    assertEquals(vars.get("result").toString(), "http://localhost:9876/homepage/home");
    driver.close();
  }
  @Test
  public void iTTD007002001() {
    driver.get("http://localhost:9876/homepage/home");
    driver.manage().window().setSize(new Dimension(1095, 755));
    driver.findElement(By.cssSelector(".section-banner-input")).click();
    driver.findElement(By.cssSelector(".section-banner-input")).sendKeys("手表");
    driver.findElement(By.cssSelector(".section-banner-button")).click();
    vars.put("result", js.executeScript("return window.location.href"));
    assertEquals(vars.get("result").toString(), "http://localhost:9876/homepage/items?mode=2&q=%E6%89%8B%E8%A1%A8");
    driver.close();
  }
  @Test
  public void iTTD007003001() {
    driver.get("http://localhost:9876/homepage/home");
    driver.manage().window().setSize(new Dimension(1095, 755));
    driver.findElement(By.cssSelector(".section-banner-input")).click();
    driver.findElement(By.cssSelector(".section-banner-input")).sendKeys("手表");
    driver.findElement(By.cssSelector(".section-banner-button")).click();
    vars.put("result", js.executeScript("return window.location.href"));
    assertEquals(vars.get("result").toString(), "http://localhost:9876/homepage/items?mode=2&q=%E6%89%8B%E8%A1%A8");
    driver.close();
  }
  @Test
  public void iTTD008001001() {
    driver.get("http://localhost:9876/homepage/home");
    driver.manage().window().setSize(new Dimension(1095, 783));
    driver.findElement(By.linkText("登录")).click();
    driver.findElement(By.cssSelector(".login-input:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".login-input:nth-child(1)")).sendKeys("zldl");
    driver.findElement(By.cssSelector(".login-input:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".login-input:nth-child(3)")).sendKeys("12345");
    driver.findElement(By.cssSelector(".login-btn")).click();
    driver.findElement(By.cssSelector(".section-banner-input")).click();
    driver.findElement(By.cssSelector(".section-banner-input")).sendKeys("相机");
    driver.findElement(By.cssSelector(".section-banner-button")).click();
    js.executeScript("window.scrollTo(0,686.4000244140625)");
    driver.findElement(By.cssSelector(".commodity-card:nth-child(1) path")).click();
    assertThat(driver.findElement(By.cssSelector(".el-message__content")).getText(), is("收藏成功"));
    driver.close();
  }
  @Test
  public void iTTD009001001() {
    driver.get("http://localhost:9876/homepage/home");
    driver.manage().window().setSize(new Dimension(1095, 783));
    driver.findElement(By.linkText("登录")).click();
    driver.findElement(By.cssSelector(".login-input:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".login-input:nth-child(1)")).sendKeys("zldl");
    driver.findElement(By.cssSelector(".login-input:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".login-input:nth-child(3)")).sendKeys("12345");
    driver.findElement(By.cssSelector(".login-btn")).click();
    driver.findElement(By.linkText("个人主页")).click();
    driver.findElement(By.linkText("收藏夹")).click();
    driver.findElement(By.cssSelector(".commodity-card:nth-child(1) .heart")).click();
    assertThat(driver.findElement(By.cssSelector(".el-message__content")).getText(), is("取消收藏成功"));
    driver.close();
  }
}
